[package]
name = "one_predict_arena"
edition = "2024.beta"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[addresses]
one_predict_arena = "0x0"

[dev-dependencies]

[dev-addresses]
